// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: set.proto

package buffs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Set struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SetlistId string `protobuf:"bytes,1,opt,name=setlist_id,json=setlistId,proto3" json:"setlist_id,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Set) Reset() {
	*x = Set{}
	if protoimpl.UnsafeEnabled {
		mi := &file_set_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Set) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Set) ProtoMessage() {}

func (x *Set) ProtoReflect() protoreflect.Message {
	mi := &file_set_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Set.ProtoReflect.Descriptor instead.
func (*Set) Descriptor() ([]byte, []int) {
	return file_set_proto_rawDescGZIP(), []int{0}
}

func (x *Set) GetSetlistId() string {
	if x != nil {
		return x.SetlistId
	}
	return ""
}

func (x *Set) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Set) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SetlistId string `protobuf:"bytes,1,opt,name=setlist_id,json=setlistId,proto3" json:"setlist_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateSetRequest) Reset() {
	*x = CreateSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_set_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSetRequest) ProtoMessage() {}

func (x *CreateSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_set_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSetRequest.ProtoReflect.Descriptor instead.
func (*CreateSetRequest) Descriptor() ([]byte, []int) {
	return file_set_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSetRequest) GetSetlistId() string {
	if x != nil {
		return x.SetlistId
	}
	return ""
}

func (x *CreateSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReadSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadSetRequest) Reset() {
	*x = ReadSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_set_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSetRequest) ProtoMessage() {}

func (x *ReadSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_set_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSetRequest.ProtoReflect.Descriptor instead.
func (*ReadSetRequest) Descriptor() ([]byte, []int) {
	return file_set_proto_rawDescGZIP(), []int{2}
}

func (x *ReadSetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UpdateSetRequest) Reset() {
	*x = UpdateSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_set_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSetRequest) ProtoMessage() {}

func (x *UpdateSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_set_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSetRequest.ProtoReflect.Descriptor instead.
func (*UpdateSetRequest) Descriptor() ([]byte, []int) {
	return file_set_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteSetRequest) Reset() {
	*x = DeleteSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_set_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSetRequest) ProtoMessage() {}

func (x *DeleteSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_set_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSetRequest.ProtoReflect.Descriptor instead.
func (*DeleteSetRequest) Descriptor() ([]byte, []int) {
	return file_set_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_set_proto protoreflect.FileDescriptor

var file_set_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x62, 0x61, 0x72,
	0x62, 0x61, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x74, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x65, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x65, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x45, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x74, 0x6c, 0x69, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x20, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x53,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x10, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x22, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0x8d, 0x02, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65,
	0x74, 0x12, 0x1d, 0x2e, 0x62, 0x61, 0x72, 0x62, 0x61, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x74, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x10, 0x2e, 0x62, 0x61, 0x72, 0x62, 0x61, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x74, 0x2e, 0x53,
	0x65, 0x74, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x07, 0x52, 0x65, 0x61, 0x64, 0x53, 0x65, 0x74, 0x12,
	0x1b, 0x2e, 0x62, 0x61, 0x72, 0x62, 0x61, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x74, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x62,
	0x61, 0x72, 0x62, 0x61, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x22, 0x00,
	0x12, 0x3e, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x12, 0x1d, 0x2e,
	0x62, 0x61, 0x72, 0x62, 0x61, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x62,
	0x61, 0x72, 0x62, 0x61, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x22, 0x00,
	0x12, 0x43, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x74, 0x12, 0x1d, 0x2e,
	0x62, 0x61, 0x72, 0x62, 0x61, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x62,
	0x61, 0x72, 0x62, 0x61, 0x6e, 0x64, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x34, 0x6e, 0x67, 0x35, 0x79, 0x2f, 0x62, 0x61, 0x72, 0x62, 0x61,
	0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x62, 0x75,
	0x66, 0x66, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_set_proto_rawDescOnce sync.Once
	file_set_proto_rawDescData = file_set_proto_rawDesc
)

func file_set_proto_rawDescGZIP() []byte {
	file_set_proto_rawDescOnce.Do(func() {
		file_set_proto_rawDescData = protoimpl.X.CompressGZIP(file_set_proto_rawDescData)
	})
	return file_set_proto_rawDescData
}

var file_set_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_set_proto_goTypes = []interface{}{
	(*Set)(nil),              // 0: barband.set.Set
	(*CreateSetRequest)(nil), // 1: barband.set.CreateSetRequest
	(*ReadSetRequest)(nil),   // 2: barband.set.ReadSetRequest
	(*UpdateSetRequest)(nil), // 3: barband.set.UpdateSetRequest
	(*DeleteSetRequest)(nil), // 4: barband.set.DeleteSetRequest
	(*Empty)(nil),            // 5: barband.common.Empty
}
var file_set_proto_depIdxs = []int32{
	1, // 0: barband.set.SetService.CreateSet:input_type -> barband.set.CreateSetRequest
	2, // 1: barband.set.SetService.ReadSet:input_type -> barband.set.ReadSetRequest
	3, // 2: barband.set.SetService.UpdateSet:input_type -> barband.set.UpdateSetRequest
	4, // 3: barband.set.SetService.DeleteSet:input_type -> barband.set.DeleteSetRequest
	0, // 4: barband.set.SetService.CreateSet:output_type -> barband.set.Set
	0, // 5: barband.set.SetService.ReadSet:output_type -> barband.set.Set
	0, // 6: barband.set.SetService.UpdateSet:output_type -> barband.set.Set
	5, // 7: barband.set.SetService.DeleteSet:output_type -> barband.common.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_set_proto_init() }
func file_set_proto_init() {
	if File_set_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_set_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Set); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_set_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_set_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_set_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_set_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_set_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_set_proto_goTypes,
		DependencyIndexes: file_set_proto_depIdxs,
		MessageInfos:      file_set_proto_msgTypes,
	}.Build()
	File_set_proto = out.File
	file_set_proto_rawDesc = nil
	file_set_proto_goTypes = nil
	file_set_proto_depIdxs = nil
}
